CREATE DATABASE `spinner`;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, FILE, INDEX, ALTER, CREATE TEMPORARY TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON *.* TO 'spinner'@'localhost' IDENTIFIED BY PASSWORD '*141D9DF92FB1325EBDBED61553DC8E2DB2D07E97';

GRANT ALL PRIVILEGES ON `spinner`.* TO 'spinner'@'localhost';

CREATE TABLE `user` (
  `Username` varchar(20) COLLATE utf8_bin NOT NULL,
  `Email` varchar(50) COLLATE utf8_bin NOT NULL,
  `Password` varchar(50) COLLATE utf8_bin NOT NULL,
  `Balance` int(11) NOT NULL DEFAULT 1000
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;